'use strict';
class MoneyGraph {
 constructor(canvas,overlay,onSelect){
  this.canvas=canvas;this.overlay=overlay;this.ctx=canvas.getContext('2d');this.fx=overlay.getContext('2d');this.onSelect=onSelect;this.points=new Map();this.edges=[];this.nodes=[];this.visible=[];this.cluster='';this.selected=null;this.near=new Set();this.focusEdges=new Set();this.removed=new Set();this.falling=new Map();this.scale=1;this.ox=0;this.oy=0;this.W=1;this.H=1;this.motion=false;this.flowPaths=[];this.cacheColors();this.bind();new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);
 }
 cacheColors(){const css=getComputedStyle(document.body);this.colors={};for(const k of ['text','muted','subtle','edge','accent','seed','canvas','coordinator','consolidator','distributor','transit','terminal','peripheral'])this.colors[k]=css.getPropertyValue('--'+k).trim()}
 setData(data){this.data=data;this.nodes=data.nodes;this.edges=data.edges;this.points=new Map();this.adj=new Map(this.nodes.map(n=>[n.gid,[]]));for(const e of this.edges){this.adj.get(e.src).push(e);if(e.src!==e.dst)this.adj.get(e.dst).push(e)}
  this.hasCoordinates=this.nodes.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y));
  if(this.hasCoordinates){for(const n of this.nodes)this.points.set(n.gid,{x:n.x*1000,y:n.y*1000,n})}
  else { // Temporary compatibility with the preceding display, until pipeline coordinates arrive.
   const groups=new Map();for(const n of this.nodes){const k=String(n.cluster_id);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(n)}const width=Math.max(900,Math.sqrt(this.nodes.length)*55);let x=0,y=0,rowH=0;for(const [,ns]of [...groups].sort((a,b)=>b[1].length-a[1].length)){ns.sort((a,b)=>b.priority_score-a.priority_score);const r=Math.max(55,Math.sqrt(ns.length)*17),size=2*r+65;if(x+size>width&&x){x=0;y+=rowH;rowH=0}ns.forEach((n,i)=>{const a=i*2.399963229728653,rr=i?Math.sqrt(i/ns.length)*r:0;this.points.set(n.gid,{x:x+r+30+Math.cos(a)*rr,y:y+r+30+Math.sin(a)*rr,n})});x+=size;rowH=Math.max(rowH,size)}
  }
  this.maxAmount=Math.max(1,...this.edges.map(e=>e.sum_kzt));this.edgeImportance=new Map(this.edges.map(e=>[e,Math.log1p(e.sum_kzt)/Math.log1p(this.maxAmount)]));this.sortedEdges=this.edges.slice().sort((a,b)=>b.sum_kzt-a.sum_kzt);
  this.seedParents=new Map();const queue=this.nodes.filter(n=>n.is_seed).map(n=>n.gid);for(const id of queue)this.seedParents.set(id,null);for(let i=0;i<queue.length;i++)for(const e of this.adj.get(queue[i]))if(e.src===queue[i]&&!this.seedParents.has(e.dst)){this.seedParents.set(e.dst,e);queue.push(e.dst)}
  this.areas=[];for(const c of data.clusters){const ps=this.nodes.filter(n=>String(n.cluster_id)===String(c.cluster_id)).map(n=>this.points.get(n.gid));if(!ps.length)continue;const cx=Number.isFinite(c.x)?c.x:Number.isFinite(c.center_x)?c.center_x:c.center?.x,cy=Number.isFinite(c.y)?c.y:Number.isFinite(c.center_y)?c.center_y:c.center?.y;this.areas.push({id:String(c.cluster_id),size:ps.length,hull:this.hull(ps),x:this.hasCoordinates&&Number.isFinite(cx)?cx*1000:ps.reduce((a,p)=>a+p.x,0)/ps.length,y:this.hasCoordinates&&Number.isFinite(cy)?cy*1000:ps.reduce((a,p)=>a+p.y,0)/ps.length,r:this.hasCoordinates&&Number.isFinite(c.radius)?c.radius*1000:null})}
  this.areas.sort((a,b)=>b.size-a.size);this.selected=null;this.near.clear();this.focusEdges.clear();this.cluster='';this.local=false;this.removed.clear();this.filteredEdges=this.sortedEdges;this.visible=[...this.points.values()];this.resize();this.fit();this.startTime=this.motion?performance.now():0;this.request();
 }
 hull(points){if(points.length<3)return points;const ps=points.slice().sort((a,b)=>a.x-b.x||a.y-b.y),cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),lower=[],upper=[];for(const p of ps){while(lower.length>=2&&cross(lower.at(-2),lower.at(-1),p)<=0)lower.pop();lower.push(p)}for(const p of ps.slice().reverse()){while(upper.length>=2&&cross(upper.at(-2),upper.at(-1),p)<=0)upper.pop();upper.push(p)}return lower.slice(0,-1).concat(upper.slice(0,-1))}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect();if(!r.width||!r.height)return;const oldW=this.W,oldH=this.H;this.W=r.width;this.H=r.height;const d=Math.min(devicePixelRatio||1,2);for(const c of [this.canvas,this.overlay]){c.width=this.W*d;c.height=this.H*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}this.ox+=(this.W-oldW)/2;this.oy+=(this.H-oldH)/2;this.request()}
 filter(cluster='',local=false){this.cluster=cluster;this.local=local;this.visible=[...this.points.values()].filter(p=>(!cluster||String(p.n.cluster_id)===cluster)&&(!local||this.near.has(p.n.gid)));const ids=new Set(this.visible.map(p=>p.n.gid));this.filteredEdges=this.sortedEdges.filter(e=>ids.has(e.src)&&ids.has(e.dst));this.fit()}
 fit(){if(!this.visible.length)return;let x0=Infinity,y0=Infinity,x1=-Infinity,y1=-Infinity;for(const p of this.visible){x0=Math.min(x0,p.x);y0=Math.min(y0,p.y);x1=Math.max(x1,p.x);y1=Math.max(y1,p.y)}this.scale=Math.min((this.W-85)/Math.max(120,x1-x0),(this.H-95)/Math.max(120,y1-y0),2.5);this.scale=Math.max(.025,this.scale);this.baseScale=this.scale;this.ox=this.W/2-(x0+x1)/2*this.scale;this.oy=(this.H-15)/2-(y0+y1)/2*this.scale;this.request()}
 select(id){if(!this.points.has(id))return;this.selected=id;this.near=new Set([id]);this.focusEdges=new Set(this.adj.get(id));for(const e of this.adj.get(id)){this.near.add(e.src);this.near.add(e.dst)}let cursor=id,guard=0;while(this.seedParents.get(cursor)&&guard++<this.nodes.length){const e=this.seedParents.get(cursor);this.focusEdges.add(e);this.near.add(e.src);this.near.add(e.dst);cursor=e.src}this.startTime=0;this.filter('');const p=this.points.get(id);let far=100;for(const e of this.adj.get(id)){const other=this.points.get(e.src===id?e.dst:e.src);far=Math.max(far,Math.hypot(other.x-p.x,other.y-p.y))}this.scale=Math.max(this.baseScale,Math.min(2,Math.min(this.W,this.H)*.39/far));this.ox=this.W/2-p.x*this.scale;this.oy=this.H/2-p.y*this.scale;this.request()}
 clear(){this.selected=null;this.near.clear();this.focusEdges.clear();this.filter('')}
 setMotion(enabled){this.motion=enabled;if(!enabled){this.startTime=0;this.falling.clear();cancelAnimationFrame(this.animation);this.animation=0;this.fx.clearRect(0,0,this.W,this.H)}else this.animate();this.request()}
 setRemoved(ids){const next=new Set(ids),now=performance.now();for(const id of next)if(!this.removed.has(id))this.falling.set(id,now);this.removed=next;this.request();if(this.motion)this.animate()}
 setDay(day){this.day=day;this.request()}
 amount(e){if(!this.day||!Array.isArray(e.daily))return e.sum_kzt;return e.daily.reduce((s,d)=>s+(d.date<=this.day?Number(d.sum_kzt)||0:0),0)}
 zoom(f,x=this.W/2,y=this.H/2){const old=this.scale;this.scale=Math.max(.025,Math.min(8,this.scale*f));this.ox=x-(x-this.ox)*this.scale/old;this.oy=y-(y-this.oy)*this.scale/old;this.startTime=0;this.request()}
 screen(p){return {x:p.x*this.scale+this.ox,y:p.y*this.scale+this.oy}}
 radius(n){const score=Math.max(0,Math.min(1,Number(n.priority_score)||0));return Math.max(1.25,Math.min(13,(1.7+score*7.2)*Math.sqrt(this.scale)))}
 request(){if(!this.frame)this.frame=requestAnimationFrame(()=>{this.frame=0;this.paint()})}
 paint(){const c=this.ctx;c.clearRect(0,0,this.W,this.H);if(!this.data)return;this.cacheColors();const colors=this.colors,now=performance.now(),intro=this.motion&&this.startTime?Math.min(1,(now-this.startTime)/1500):1;this.flowPaths=[];
  // Region envelopes follow supplied node coordinates; this never moves nodes.
  for(const [i,a]of this.areas.entries()){if(this.cluster&&this.cluster!==a.id||a.size<3)continue;if(a.hull.length<3)continue;c.beginPath();a.hull.forEach((p,j)=>{const q=this.screen(p);j?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y)});c.closePath();c.fillStyle=colors.edge;c.globalAlpha=this.selected?.015:.035;c.fill();c.strokeStyle=colors.edge;c.lineWidth=.7;c.globalAlpha=this.selected?.035:.16;c.stroke();if((i<8||this.cluster)&&!this.selected){const p=this.screen({x:a.x,y:Math.min(...a.hull.map(p=>p.y))});if(p.x>30&&p.x<this.W-40&&p.y>25&&p.y<this.H-35){c.globalAlpha=.8;c.font='9px system-ui';c.fillStyle=colors.muted;c.fillText('КЛАСТЕР '+a.id,p.x-25,p.y-9)}}}
  const mobile=this.W<600,overview=this.scale<(this.hasCoordinates?.7:.35),limit=this.selected?2000:mobile?180:500;let drawn=0;
  for(const e of this.filteredEdges){const focused=this.focusEdges.has(e);if(this.selected&&!focused)continue;if(this.removed.has(e.src)||this.removed.has(e.dst)||!this.amount(e))continue;if(!focused&&drawn>=limit)continue;const pa=this.points.get(e.src),pb=this.points.get(e.dst);if(intro<1&&Math.max(pa.n.depth,pb.n.depth)/5>intro)continue;const a=this.screen(pa),b=this.screen(pb);if((a.x< -20&&b.x< -20)||(a.x>this.W+20&&b.x>this.W+20)||(a.y< -20&&b.y< -20)||(a.y>this.H+20&&b.y>this.H+20))continue;const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(len<3)continue;drawn++;const ux=dx/len,uy=dy/len,r=this.radius(pb.n)+2,end={x:b.x-ux*r,y:b.y-uy*r},bend=Math.min(44,len*.15),cp={x:(a.x+end.x)/2-uy*bend,y:(a.y+end.y)/2+ux*bend},importance=this.edgeImportance.get(e),hue=focused?colors.accent:colors[pa.n.role]||colors.edge;
   c.globalAlpha=focused?.7:overview?.13:.22;c.strokeStyle=hue;c.lineWidth=focused?1+importance*1.5:.35+importance*1.2;c.beginPath();c.moveTo(a.x,a.y);c.quadraticCurveTo(cp.x,cp.y,end.x,end.y);c.stroke();if(focused||!overview||importance>.82){const tx=end.x-cp.x,ty=end.y-cp.y,l=Math.hypot(tx,ty),vx=tx/l,vy=ty/l,s=focused?5.5:3.5;c.globalAlpha=focused?.95:.48;c.fillStyle=hue;c.beginPath();c.moveTo(end.x,end.y);c.lineTo(end.x-vx*s-vy*s*.45,end.y-vy*s+vx*s*.45);c.lineTo(end.x-vx*s+vy*s*.45,end.y-vy*s-vx*s*.45);c.fill()}
   if(this.flowPaths.length<(mobile?30:80)&&(focused||importance>.72))this.flowPaths.push({a,b:end,c:cp,color:hue,speed:.08+importance*.13,phase:(drawn*.618)%1});
  }
  for(const p of this.visible){const n=p.n,id=n.gid,q=this.screen(p),r=this.radius(n);if(q.x< -20||q.y< -20||q.x>this.W+20||q.y>this.H+20)continue;const reveal=intro===1?1:Math.max(0,Math.min(1,(intro-Number(n.depth||0)*.16)*5));if(!reveal)continue;const gone=this.removed.has(id),fall=this.falling.get(id),t=fall&&this.motion?Math.min(1,(now-fall)/650):1;c.globalAlpha=(gone?.08:!this.selected||this.near.has(id)?1:.10)*reveal;c.fillStyle=colors[n.role]||colors.peripheral;let yy=q.y+(gone&&t<1?t*t*25:0);c.beginPath();c.arc(q.x,yy,r*(gone&&t<1?1-t*.7:1)*reveal,0,Math.PI*2);c.fill();if(n.is_seed||id===this.selected){c.strokeStyle=id===this.selected?colors.accent:colors.seed;c.lineWidth=id===this.selected?1.6:.85;c.beginPath();c.arc(q.x,yy,r+2.6,0,Math.PI*2);c.stroke()}if(id===this.selected){c.globalAlpha=1;c.font='11px ui-monospace,monospace';const text=id,tw=c.measureText(text).width,x=Math.min(this.W-tw-14,Math.max(4,q.x+r+8));c.fillStyle=colors.canvas;c.fillRect(x-5,q.y-10,tw+10,20);c.fillStyle=colors.text;c.fillText(text,x,q.y+4)}}c.globalAlpha=1;this.lastPaint=now;if(this.motion)this.animate();
 }
 animate(){if(this.animation||!this.motion||document.hidden)return;this.animation=requestAnimationFrame(now=>{this.animation=0;if(!this.motion)return;if(now-(this.lastFlow||0)<32){this.animate();return}this.lastFlow=now;const ctx=this.fx;ctx.clearRect(0,0,this.W,this.H);if(this.canvas.closest('[hidden]'))return;for(const path of this.flowPaths){const t=(now*.001*path.speed+path.phase)%1,u=1-t,x=u*u*path.a.x+2*u*t*path.c.x+t*t*path.b.x,y=u*u*path.a.y+2*u*t*path.c.y+t*t*path.b.y;ctx.globalAlpha=.8;ctx.fillStyle=path.color;ctx.beginPath();ctx.arc(x,y,this.selected?2:1.5,0,Math.PI*2);ctx.fill()}const assembling=this.startTime&&now-this.startTime<1500,falling=[...this.falling.values()].some(t=>now-t<650);if((assembling||falling)&&now-this.lastPaint>65)this.request();this.animate()})}
 bind(){const c=this.canvas,pointers=new Map();let start=null,dragged=false;c.addEventListener('wheel',e=>{e.preventDefault();const r=c.getBoundingClientRect();this.zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)},{passive:false});c.onpointerdown=e=>{c.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});start={x:e.clientX,y:e.clientY};dragged=false};c.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId),other=[...pointers.entries()].find(([id])=>id!==e.pointerId)?.[1];if(other){const before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y),r=c.getBoundingClientRect();if(before)this.zoom(after/before,(e.clientX+other.x)/2-r.left,(e.clientY+other.y)/2-r.top);dragged=true}else{this.ox+=e.clientX-old.x;this.oy+=e.clientY-old.y;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>4)dragged=true;this.request()}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY})};c.onpointerup=e=>{pointers.delete(e.pointerId);if(dragged||pointers.size)return;const r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let hit,best=Infinity;for(const p of this.visible){const q=this.screen(p),distance=Math.hypot(x-q.x,y-q.y);if(distance<Math.max(9,this.radius(p.n)+3)&&distance<best){hit=p;best=distance}}if(hit)this.onSelect(hit.n.gid)};c.onpointercancel=e=>{pointers.delete(e.pointerId);dragged=true};document.addEventListener('visibilitychange',()=>{if(!document.hidden)this.animate()})}
}
