'use strict';
class MoneyGraph {
 constructor(canvas,overlay,onSelect){
  this.canvas=canvas;this.overlay=overlay;this.ctx=canvas.getContext('2d');this.fx=overlay.getContext('2d');this.onSelect=onSelect;this.points=new Map();this.edges=[];this.nodes=[];this.visible=[];this.cluster='';this.selected=null;this.near=new Set();this.focusEdges=new Set();this.removed=new Set();this.falling=new Map();this.scale=1;this.ox=0;this.oy=0;this.W=1;this.H=1;this.motion=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.hover=null;this.hoverNear=new Set();this.flowPaths=[];this.cacheColors();this.bind();new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);
 }
 cacheColors(){const css=getComputedStyle(document.body);this.colors={};for(const k of ['text','muted','subtle','edge','accent','seed','canvas','coordinator','consolidator','distributor','transit','terminal','peripheral'])this.colors[k]=css.getPropertyValue('--'+k).trim()}
 setData(data){if(!data||!Array.isArray(data.nodes)||!Array.isArray(data.edges)||data.nodes.some(n=>typeof n.gid!=='string'||!Number.isFinite(n.x)||!Number.isFinite(n.y)))throw new Error('Некорректные идентификаторы или координаты сети');this.data=data;this.nodes=data.nodes;const validIds=new Set(this.nodes.map(n=>n.gid));this.edges=data.edges.filter(e=>validIds.has(e.src)&&validIds.has(e.dst));this.points=new Map();this.adj=new Map(this.nodes.map(n=>[n.gid,[]]));for(const e of this.edges){this.adj.get(e.src).push(e);if(e.src!==e.dst)this.adj.get(e.dst).push(e)}
  this.hasCoordinates=this.nodes.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y));
  for(const n of this.nodes)this.points.set(n.gid,{x:n.x*1000,y:(1-n.y)*1000,n});
  this.maxAmount=Math.max(1,...this.edges.map(e=>e.sum_kzt));this.edgeImportance=new Map(this.edges.map(e=>[e,Math.log1p(e.sum_kzt)/Math.log1p(this.maxAmount)]));this.sortedEdges=this.edges.slice().sort((a,b)=>b.sum_kzt-a.sum_kzt);
  this.seedParents=new Map();const queue=this.nodes.filter(n=>n.is_seed).map(n=>n.gid);for(const id of queue)this.seedParents.set(id,null);for(let i=0;i<queue.length;i++)for(const e of this.adj.get(queue[i]))if(e.src===queue[i]&&!this.seedParents.has(e.dst)){this.seedParents.set(e.dst,e);queue.push(e.dst)}
  this.areas=[];for(const c of data.clusters||[]){const ps=this.nodes.filter(n=>String(n.cluster_id)===String(c.cluster_id)).map(n=>this.points.get(n.gid));if(!ps.length)continue;const cx=Number.isFinite(c.x)?c.x:Number.isFinite(c.center_x)?c.center_x:c.center?.x,cy=Number.isFinite(c.y)?c.y:Number.isFinite(c.center_y)?c.center_y:c.center?.y;this.areas.push({id:String(c.cluster_id),size:ps.length,hull:this.hull(ps),x:this.hasCoordinates&&Number.isFinite(cx)?cx*1000:ps.reduce((a,p)=>a+p.x,0)/ps.length,y:this.hasCoordinates&&Number.isFinite(cy)?(1-cy)*1000:ps.reduce((a,p)=>a+p.y,0)/ps.length,r:this.hasCoordinates&&Number.isFinite(c.radius)?c.radius*1000:null})}
  this.areas.sort((a,b)=>b.size-a.size);this.selected=null;this.near.clear();this.focusEdges.clear();this.cluster='';this.local=false;this.removed.clear();this.filteredEdges=this.sortedEdges;this.visible=[...this.points.values()];this.resize();this.fit();this.startTime=this.motion?performance.now():0;this.request();
 }
 hull(points){if(points.length<3)return points;const ps=points.slice().sort((a,b)=>a.x-b.x||a.y-b.y),cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),lower=[],upper=[];for(const p of ps){while(lower.length>=2&&cross(lower.at(-2),lower.at(-1),p)<=0)lower.pop();lower.push(p)}for(const p of ps.slice().reverse()){while(upper.length>=2&&cross(upper.at(-2),upper.at(-1),p)<=0)upper.pop();upper.push(p)}return lower.slice(0,-1).concat(upper.slice(0,-1))}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect();if(!r.width||!r.height)return;const oldW=this.W,oldH=this.H;this.W=r.width;this.H=r.height;const d=Math.min(devicePixelRatio||1,2);for(const c of [this.canvas,this.overlay]){c.width=this.W*d;c.height=this.H*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}if(!this.userView&&this.visible.length)this.fit();else{this.ox+=(this.W-oldW)/2;this.oy+=(this.H-oldH)/2;this.request()}}
 filter(cluster='',local=false){this.cluster=cluster;this.local=local;this.visible=[...this.points.values()].filter(p=>(!cluster||String(p.n.cluster_id)===cluster)&&(!local||this.near.has(p.n.gid)));const ids=new Set(this.visible.map(p=>p.n.gid));this.filteredEdges=this.sortedEdges.filter(e=>ids.has(e.src)&&ids.has(e.dst));this.fit()}
 fit(){this.userView=false;cancelAnimationFrame(this.inertia);this.inertia=0;this.zoomTarget=null;if(!this.visible.length){this.request();return;}let x0=Infinity,y0=Infinity,x1=-Infinity,y1=-Infinity;for(const p of this.visible){x0=Math.min(x0,p.x);y0=Math.min(y0,p.y);x1=Math.max(x1,p.x);y1=Math.max(y1,p.y)}const px=this.W<500?64:110,top=50,bottom=65;this.scale=Math.min(Math.max(60,this.W-px*2)/Math.max(120,x1-x0),Math.max(60,this.H-top-bottom)/Math.max(120,y1-y0),2.5);this.scale=Math.max(.025,this.scale);this.baseScale=this.scale;this.ox=this.W/2-(x0+x1)/2*this.scale;this.oy=(this.H+top-bottom)/2-(y0+y1)/2*this.scale;this.request()}
 select(id){if(!this.points.has(id))return;this.selected=id;this.near=new Set([id]);this.focusEdges=new Set(this.adj.get(id));for(const e of this.adj.get(id)){this.near.add(e.src);this.near.add(e.dst)}let cursor=id,guard=0;while(this.seedParents.get(cursor)&&guard++<this.nodes.length){const e=this.seedParents.get(cursor);this.focusEdges.add(e);this.near.add(e.src);this.near.add(e.dst);cursor=e.src}this.startTime=0;this.hover=null;this.filter('',true);this.request()}
 clear(){this.hover=null;this.selected=null;this.near.clear();this.focusEdges.clear();this.filter('')}
 setMotion(enabled){this.motion=enabled&&!this.reduced;if(!this.motion){this.startTime=0;this.falling.clear();cancelAnimationFrame(this.animation);this.animation=0;this.fx.clearRect(0,0,this.W,this.H)}else this.animate();this.request()}
 setRemoved(ids){const next=new Set(ids),now=performance.now();for(const id of next)if(!this.removed.has(id))this.falling.set(id,now);this.removed=next;this.request();if(this.motion)this.animate()}
 setDay(day){this.day=day;this.request()}
 amount(e){if(!this.day||!Array.isArray(e.daily))return e.sum_kzt;return e.daily.reduce((s,d)=>s+(d.date<=this.day?Number(d.sum_kzt)||0:0),0)}
 zoom(f,x=this.W/2,y=this.H/2){this.userView=true;if(arguments.length===1&&!this.reduced){this.smoothZoom(f,x,y);return}const old=this.scale;this.scale=Math.max(Math.max(.025,(this.baseScale||.1)*.45),Math.min(Math.max(8,this.baseScale||1),this.scale*f));this.ox=x-(x-this.ox)*this.scale/old;this.oy=y-(y-this.oy)*this.scale/old;this.startTime=0;this.request()}
 screen(p){return {x:p.x*this.scale+this.ox,y:p.y*this.scale+this.oy}}
 radius(n){const score=Math.max(0,Math.min(1,Number(n.priority_score)||0));return Math.max(1.25,Math.min(13,(1.7+score*7.2)*Math.sqrt(this.scale)))}
 request(){if(!this.frame)this.frame=requestAnimationFrame(()=>{this.frame=0;this.paint()})}
 paint(){const c=this.ctx;c.clearRect(0,0,this.W,this.H);if(!this.data)return;this.cacheColors();const colors=this.colors,now=performance.now(),intro=this.motion&&this.startTime?Math.min(1,(now-this.startTime)/1500):1;this.flowPaths=[];this.edgeLabels=[];
  // Region envelopes follow supplied node coordinates; this never moves nodes.
  for(const [i,a]of this.areas.entries()){if(this.local)continue;if(this.cluster&&this.cluster!==a.id||a.size<3)continue;if(a.hull.length<3)continue;c.beginPath();a.hull.forEach((p,j)=>{const q=this.screen(p);j?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y)});c.closePath();c.fillStyle=colors.edge;c.globalAlpha=this.selected?.015:.035;c.fill();c.strokeStyle=colors.edge;c.lineWidth=.7;c.globalAlpha=this.selected?.035:.16;c.stroke();if((i<8||this.cluster)&&!this.selected){const p=this.screen({x:a.x,y:Math.min(...a.hull.map(p=>p.y))});if(p.x>30&&p.x<this.W-40&&p.y>25&&p.y<this.H-35){c.globalAlpha=.8;c.font='9px system-ui';c.fillStyle=colors.muted;c.fillText('КЛАСТЕР '+a.id,p.x-25,p.y-9)}}}
  const mobile=this.W<600,overview=this.scale<(this.hasCoordinates?.7:.35),limit=this.selected||!overview?Infinity:mobile?180:500;let drawn=0;
  for(const e of this.filteredEdges){const hovered=this.hover&&(e.src===this.hover||e.dst===this.hover),focused=this.focusEdges.has(e)||hovered;if(this.selected&&!focused)continue;if(this.removed.has(e.src)||this.removed.has(e.dst)||!this.amount(e))continue;if(!focused&&drawn>=limit)continue;const pa=this.points.get(e.src),pb=this.points.get(e.dst);if(intro<1&&Math.max(pa.n.depth,pb.n.depth)/5>intro)continue;const a=this.screen(pa),b=this.screen(pb);if((a.x< -20&&b.x< -20)||(a.x>this.W+20&&b.x>this.W+20)||(a.y< -20&&b.y< -20)||(a.y>this.H+20&&b.y>this.H+20))continue;const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(len<3)continue;drawn++;const ux=dx/len,uy=dy/len,r=this.radius(pb.n)+2,end={x:b.x-ux*r,y:b.y-uy*r},bend=Math.min(44,len*.15),cp={x:(a.x+end.x)/2-uy*bend,y:(a.y+end.y)/2+ux*bend},importance=this.edgeImportance.get(e),hue=focused?colors.accent:colors.edge;
   c.globalAlpha=hovered?1:focused?.82:this.hover?.07:overview?.18:.3;c.strokeStyle=hue;c.lineWidth=focused?1+importance*1.5:.35+importance*1.2;c.beginPath();c.moveTo(a.x,a.y);c.quadraticCurveTo(cp.x,cp.y,end.x,end.y);c.stroke();if(focused||!overview||importance>.82){const tx=end.x-cp.x,ty=end.y-cp.y,l=Math.hypot(tx,ty),vx=tx/l,vy=ty/l,s=focused?8:4.5;c.globalAlpha=focused?.95:.48;c.fillStyle=hue;c.beginPath();c.moveTo(end.x,end.y);c.lineTo(end.x-vx*s-vy*s*.45,end.y-vy*s+vx*s*.45);c.lineTo(end.x-vx*s+vy*s*.45,end.y-vy*s-vx*s*.45);c.fill()}
   if(this.local&&this.edgeLabels.length<5&&len>90)this.edgeLabels.push({x:.25*a.x+.5*cp.x+.25*end.x,y:.25*a.y+.5*cp.y+.25*end.y,text:this.money(this.amount(e))});
   if(this.flowPaths.length<(mobile?30:80)&&(focused||importance>.72))this.flowPaths.push({a,b:end,c:cp,color:hue,speed:.08+importance*.13,phase:(drawn*.618)%1});
  }
  for(const p of this.visible){const n=p.n,id=n.gid,q=this.screen(p),r=this.radius(n);if(q.x< -20||q.y< -20||q.x>this.W+20||q.y>this.H+20)continue;const reveal=intro===1?1:Math.max(0,Math.min(1,(intro-Number(n.depth||0)*.16)*5));if(!reveal)continue;const gone=this.removed.has(id),fall=this.falling.get(id),t=fall&&this.motion?Math.min(1,(now-fall)/650):1;c.globalAlpha=(gone?.08:!this.selected||this.near.has(id)?1:.10)*reveal;if(this.hover&&!this.hoverNear.has(id))c.globalAlpha*=.25;c.fillStyle=id===this.selected||n.is_seed?colors.accent:colors.muted;let yy=q.y+(gone&&t<1?t*t*25:0);c.beginPath();c.arc(q.x,yy,r*(gone&&t<1?1-t*.7:1)*reveal,0,Math.PI*2);c.fill();if(n.is_seed||id===this.selected){c.strokeStyle=id===this.selected?colors.accent:colors.seed;c.lineWidth=id===this.selected?1.6:.85;c.beginPath();c.arc(q.x,yy,r+2.6,0,Math.PI*2);c.stroke()}}c.globalAlpha=1;this.paintLabels();this.paintTooltip();this.lastPaint=now;if(this.motion)this.animate();
 }
 animate(){if(this.animation||!this.motion||document.hidden)return;this.animation=requestAnimationFrame(now=>{this.animation=0;if(!this.motion)return;if(now-(this.lastFlow||0)<32){this.animate();return}this.lastFlow=now;const ctx=this.fx;ctx.clearRect(0,0,this.W,this.H);if(this.canvas.closest('[hidden]'))return;for(const path of this.flowPaths){const t=(now*.001*path.speed+path.phase)%1,u=1-t,x=u*u*path.a.x+2*u*t*path.c.x+t*t*path.b.x,y=u*u*path.a.y+2*u*t*path.c.y+t*t*path.b.y;ctx.globalAlpha=.8;ctx.fillStyle=path.color;ctx.beginPath();ctx.arc(x,y,this.selected?2:1.5,0,Math.PI*2);ctx.fill()}const assembling=this.startTime&&now-this.startTime<1500,falling=[...this.falling.values()].some(t=>now-t<650);if((assembling||falling)&&now-this.lastPaint>65)this.request();this.animate()})}
 paintLabels(){if(!this.local)return;const c=this.ctx,boxes=[],gap=5,top=43,bottom=this.H-62,roles={coordinator:'Координатор',consolidator:'Консолидация',transit:'Транзит',distributor:'Распределитель',terminal:'Получатель',peripheral:'Периферия'};const nodes=this.visible.filter(p=>!this.removed.has(p.n.gid)).sort((a,b)=>(b.n.gid===this.selected)-(a.n.gid===this.selected)||(b.n.priority_score||0)-(a.n.priority_score||0));const obstacles=nodes.map(p=>{const q=this.screen(p),r=this.radius(p.n)+4;return {x:q.x-r,y:q.y-r,w:r*2,h:r*2}});const overlaps=(a,b)=>a.x<b.x+b.w+gap&&a.x+a.w+gap>b.x&&a.y<b.y+b.h+gap&&a.y+a.h+gap>b.y;let count=0;
  for(const p of nodes){if(count>=18)break;const q=this.screen(p),selected=p.n.gid===this.selected;if(q.x<0||q.x>this.W||q.y<top||q.y>bottom)continue;const text=selected?p.n.gid:'…'+p.n.gid.slice(-9),role=roles[p.n.role]||p.n.role;c.font='12px ui-monospace,monospace';const w=Math.max(c.measureText(text).width,c.measureText(role).width)+12,h=36,r=this.radius(p.n)+9;const candidates=[{x:q.x+r,y:q.y-h/2},{x:q.x-r-w,y:q.y-h/2},{x:q.x-w/2,y:q.y-r-h},{x:q.x-w/2,y:q.y+r},{x:q.x+r,y:q.y-r-h},{x:q.x-r-w,y:q.y+r}].map(a=>({...a,w,h}));let box=candidates.find(a=>a.x>=9&&a.x+w<this.W-9&&a.y>=top&&a.y+h<bottom&&!boxes.some(b=>overlaps(a,b))&&!obstacles.some(b=>overlaps(a,b)));if(!box&&selected)box={x:Math.max(9,Math.min(this.W-w-9,q.x+r)),y:Math.max(top,Math.min(bottom-h,q.y-h/2)),w,h};if(!box)continue;boxes.push(box);count++;c.globalAlpha=.94;c.fillStyle=this.colors.canvas;c.fillRect(box.x-2,box.y-2,w+4,h+4);c.globalAlpha=1;c.fillStyle=selected?this.colors.accent:this.colors.text;c.font=selected?'bold 12px ui-monospace,monospace':'12px ui-monospace,monospace';c.fillText(text,box.x+6,box.y+13);c.font='11px system-ui';c.fillStyle=this.colors.muted;c.fillText(role,box.x+6,box.y+29)}
  c.font='11px system-ui';for(const e of this.edgeLabels||[]){const w=c.measureText(e.text).width+12,box={x:e.x-w/2,y:e.y-10,w,h:20};if(box.x<9||box.x+w>this.W-9||box.y<top||box.y+20>bottom||boxes.some(b=>overlaps(box,b))||obstacles.some(b=>overlaps(box,b)))continue;boxes.push(box);c.fillStyle=this.colors.canvas;c.globalAlpha=.97;c.fillRect(box.x,box.y,box.w,box.h);c.globalAlpha=1;c.fillStyle=this.colors.text;c.fillText(e.text,box.x+6,box.y+14)}
 }
 smoothZoom(f,x,y){this.zoomTarget=Math.max(Math.max(.025,(this.baseScale||.1)*.45),Math.min(Math.max(8,this.baseScale||1),(this.zoomTarget||this.scale)*f));this.zoomAnchor={x,y};if(this.reduced){this.zoom(this.zoomTarget/this.scale,x,y);this.zoomTarget=null;return}if(this.zoomFrame)return;const tick=()=>{this.zoomFrame=0;if(!this.zoomTarget)return;const target=this.zoomTarget,a=this.zoomAnchor,next=this.scale+(target-this.scale)*.3;this.zoom(next/this.scale,a.x,a.y);if(Math.abs(target-this.scale)>.001)this.zoomFrame=requestAnimationFrame(tick);else{this.zoom(target/this.scale,a.x,a.y);this.zoomTarget=null}};this.zoomFrame=requestAnimationFrame(tick)}
 hit(x,y){let hit=null,best=Infinity;for(const p of this.visible){if(this.removed.has(p.n.gid))continue;const q=this.screen(p),d=Math.hypot(x-q.x,y-q.y);if(d<Math.max(12,this.radius(p.n)+5)&&d<best){hit=p;best=d}}return hit}
 paintTooltip(){if(!this.hover)return;const p=this.points.get(this.hover);if(!p)return;const c=this.ctx,q=this.screen(p),n=p.n,role=this.data.roles?.[n.role]?.label||n.role,lines=[n.gid,role,'Вход '+this.money(n.in_kzt)+' · Выход '+this.money(n.out_kzt)];c.font='12px system-ui';const w=Math.min(this.W-16,Math.max(...lines.map(t=>c.measureText(t).width))+24),x=Math.max(8,Math.min(this.W-w-8,q.x+15)),y=Math.max(8,Math.min(this.H-78,q.y-76));c.globalAlpha=1;c.fillStyle=this.colors.canvas;c.fillRect(x,y,w,70);c.strokeStyle=this.colors.subtle||this.colors.edge;c.lineWidth=1;c.strokeRect(x+.5,y+.5,w,70);lines.forEach((t,i)=>{c.fillStyle=i?this.colors.muted:this.colors.text;c.font=i?'12px system-ui':'12px ui-monospace,monospace';c.fillText(t,x+12,y+19+i*20,w-24)})}
 money(v){return new Intl.NumberFormat('ru-RU',{notation:'compact',maximumFractionDigits:1}).format(Number(v)||0)+' ₸'}
 bind(){const c=this.canvas,pointers=new Map();let start=null,dragged=false,lastTime=0,vx=0,vy=0;const stop=()=>{cancelAnimationFrame(this.inertia);this.inertia=0;vx=vy=0};c.style.touchAction='none';c.style.cursor='grab';
  c.addEventListener('wheel',e=>{e.preventDefault();stop();const r=c.getBoundingClientRect(),delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?this.H:1),factor=Math.exp(-Math.max(-160,Math.min(160,delta))*.002);this.smoothZoom(factor,e.clientX-r.left,e.clientY-r.top)},{passive:false});
  c.onpointerdown=e=>{stop();this.zoomTarget=null;c.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});start={x:e.clientX,y:e.clientY};dragged=pointers.size>1;lastTime=performance.now();this.hover=null;c.style.cursor='grabbing';this.request()};
  c.onpointermove=e=>{const r=c.getBoundingClientRect();if(!pointers.has(e.pointerId)){const hit=this.hit(e.clientX-r.left,e.clientY-r.top),id=hit?.n.gid||null;if(id!==this.hover){this.hover=id;this.hoverNear=new Set(id?[id]:[]);for(const edge of this.adj?.get(id)||[]){this.hoverNear.add(edge.src);this.hoverNear.add(edge.dst)}c.style.cursor=id?'pointer':'grab';this.request()}return}const old=pointers.get(e.pointerId),other=[...pointers.entries()].find(([id])=>id!==e.pointerId)?.[1],dx=e.clientX-old.x,dy=e.clientY-old.y,now=performance.now(),dt=Math.max(8,now-lastTime);if(other){const before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y),mx=(old.x+other.x)/2-r.left,my=(old.y+other.y)/2-r.top;if(before)this.zoom(after/before,mx,my);this.ox+=dx/2;this.oy+=dy/2;dragged=true;vx=vy=0}else{this.ox+=dx;this.oy+=dy;vx=.6*vx+.4*dx/dt;vy=.6*vy+.4*dy/dt;if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>4){dragged=true;this.userView=true}}lastTime=now;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});this.request()};
  c.onpointerup=e=>{pointers.delete(e.pointerId);c.style.cursor='grab';if(pointers.size){dragged=true;return}if(!dragged){const r=c.getBoundingClientRect(),hit=this.hit(e.clientX-r.left,e.clientY-r.top);if(hit)this.onSelect(hit.n.gid);return}if(this.reduced||performance.now()-lastTime>90)return;let previous=performance.now();const coast=now=>{const dt=Math.min(32,now-previous);previous=now;this.ox+=vx*dt;this.oy+=vy*dt;const decay=Math.exp(-dt/170);vx*=decay;vy*=decay;this.request();if(Math.hypot(vx,vy)>.012)this.inertia=requestAnimationFrame(coast);else this.inertia=0};this.inertia=requestAnimationFrame(coast)};
  c.onpointercancel=e=>{pointers.delete(e.pointerId);dragged=true;stop();c.style.cursor='grab'};c.onpointerleave=()=>{this.hover=null;this.request()};document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();this.zoomTarget=null}else this.animate()});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{this.reduced=e.matches;if(e.matches){stop();this.setMotion(false)}})
 }
}
