'use strict';
function renderTerminal(){
 const summary=summarizeTerminal(data.nodes),count=summary.counts;
 if(summary.missing===data.nodes.length){$('terminal-content').innerHTML='<p class="note">Статусы границы наблюдения ещё не рассчитаны. Обновите данные после завершения расчёта.</p>';return}
 const maximum=Math.max(1,...Object.values(count));
 const bars=Object.entries(terminalStatuses).map(([key,status])=>'<div class="status-bar"><div><strong>'+status.label+'</strong><b>'+fmt(count[key])+'</b></div><div class="bar-track"><div style="width:'+(count[key]/maximum*100)+'%;background:'+status.color+'"></div></div><p>'+status.hint+'</p></div>').join('');
 const threshold=data.meta?.method?.thresholds?.terminal_p_min?.value;
 const thresholdText=typeof threshold==='number'?' Порог назначения роли для обрезанного узла в текущем расчёте: '+pct(threshold)+'.':'';
 $('terminal-content').innerHTML=(summary.missing?'<p class="note">У '+fmt(summary.missing)+' клиентов статус отсутствует или неизвестен. Разбивка неполная.</p>':'')+
 '<div class="terminal-overview"><div class="status-bars" aria-label="Распределение статусов по всей сети">'+bars+'</div><div class="terminal-comparison"><div class="comparison-card naive"><span>Наивно: получил, но не отдал</span><strong>'+fmt(summary.naive)+'</strong><p>Всех таких клиентов записали бы в конечные получатели.</p></div><div class="comparison-card"><span>С учётом границы наблюдения</span><strong>'+fmt(summary.corrected)+'</strong><p>'+fmt(count.observed_sink)+' наблюдаемых стоков + '+fmt(summary.estimated)+' кандидатов среди обрезанных узлов, которым модель назначила роль конечного получателя.</p></div></div></div>'+
 '<p class="note">У '+fmt(count.unknown_truncated)+' узлов обход закончился на границе глубины. Закончилась выгрузка, а не обязательно движение денег. Из них '+fmt(summary.estimated)+' получили роль конечного получателя; '+fmt(count.unknown_truncated-summary.estimated)+' не получили эту роль. Для каждого обрезанного узла показываем вероятность, а не установленный факт.</p>'+
 '<details class="terminal-method"><summary>Как читать вероятность и почему число ролей отличается</summary><p>Вероятность рассчитана логистической регрессией по входящему профилю клиента и профилю его плательщиков, с обучением на коленах 1–3. Это оценка модели: продолжение переводов за пределами выгрузки неизвестно.'+thresholdText+'</p><p>Статус наблюдения и аналитическая роль — разные показатели. В текущей выгрузке роль «Конечный получатель» имеют '+fmt(summary.terminalRoles)+' клиентов: '+fmt(summary.forwardingTerminals)+' из них передают часть денег дальше; '+fmt(summary.observedOtherRoles)+' наблюдаемых стоков получили другую структурную роль. Поэтому '+fmt(summary.corrected)+' в сравнении выше — наблюдаемые стоки плюс кандидаты за границей обхода, а не количество ролей terminal.</p><p>Наблюдаемый сток тоже относится только к данной выборке: внешние и более поздние переводы здесь не видны.</p></details>'+
 '<h3>Обрезанные узлы · '+fmt(summary.truncated.length)+'</h3><p class="terminal-caption">По убыванию вероятности. Выберите gid, чтобы открыть досье и связи.</p><div class="table-wrap"><table><thead><tr><th>Клиент · gid</th><th>Вероятность стока</th><th>Роль в расчёте</th><th>Получил</th></tr></thead><tbody>'+summary.truncated.map(n=>'<tr data-gid="'+esc(n.gid)+'"><td><button data-gid="'+esc(n.gid)+'">'+esc(n.gid)+'</button></td><td>'+ (n.terminal_p==null?'Не рассчитана':pct(n.terminal_p))+'</td><td>'+esc(role(n.role))+'</td><td>'+money(n.in_kzt)+'</td></tr>').join('')+'</tbody></table></div>';
}
